language: node_js
node_js:
- '0.10'
- '0.12'
- '5'
deploy:
  provider: npm
  email:
    secure: NQ7mta8ytdnZz65yRdAv4tvq079IVGaegD+QaWdIeNgAta+6nqLLBkVRVHRcoQgwsLLGJ40ggRVGIeAb4f+d8TycVBZZwrsLDI9xmJtWCh1nr0vqHNt+IA8cwyEQNF9zyAR/o16tMXtCEVNw8JjpwD+NVoHftoq/nM+xlnKlXeM=
  api_key:
    secure: FAiPYQhL4inAEOPb7xVdT9sIB4Kvy+z/XxoORnPV8JpfcTvWPcwzt2fO+K9CI1tQAw1Dw7WJfZlktDM/GcLQ89c/l8Jcm+ARVCQHGWLZc8EoxJ0rsqrPPqrIGUURVlEuiNjD5ozaRm+tOB5vanslC/1P3i7k6v5MMYTzsEQgox8=
  on:
    tags: true
    repo: sass/node-sass-middleware
    branch: master
    all_branches: true
env:
  global:
    secure: Vp1DfqhC1cVvn1gTUEfclO7N1rRzF8AvIHaRqVUWYeWucXU/ihlgQ6TjyoVCEdcZikMGR80IDjiMY2UXeoBFX45atbpErllkQpyuPop/dGOX+lxXXAFjaCYDR07uB+HJbm/QFLYLxqr2UORD+u63w50sV/ltb6inhYtuLDO2DIs=
